In [25]:
#_________________________________TABLA DE PELICULAS__________________________________
import pandas as pd

url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTdiUa0YP6H3pX_TMLotcM-jjt3XJiMdeFXIVgQuPpsc6dyLukGeQpHmI2Iy5sZmXaTACH9kP9LQCwE/pub?output=csv'

tablaPeliculas = pd.read_csv(url)

tablaPeliculas.head()

,Titulo,Year,Director,duration,genre,rate
0,"Star Wars: Episode IV - A New Hope""",1977,"""George Lucas"",","""2h 1min""","Action, Sci-Fi Adventure, Fantasy,","8.7,"

In [26]:
#_________________________________TABLA NORMALIZADA: GENERO NUEVA TABLA__________________________________
#
tabla = [{"primary key": 1, 'Nombre': "George Lucas",	'nacimiento': "14/05/1944", "Nacionalidad": "Americano"}]

tablaDirector = pd.DataFrame(tabla)

tablaDirector.head()

   primary key        Nombre  nacimiento Nacionalidad
0            1  George Lucas  14/05/1944    Americano

In [27]:
#_________________________________TABLA DE PELICULAS CON CLAVE FORANEA__________________________________

tablaPeliculas = tablaPeliculas.rename(columns={'Director': 'foreing key'})

tablaPeliculas['foreing key'] = 1

tablaPeliculas.head()

,Titulo,Year,foreing key,duration,genre,rate
0,"Star Wars: Episode IV - A New Hope""",1977,1,"""2h 1min""","Action, Sci-Fi Adventure, Fantasy,","8.7,"